POST http://localhost:3001/api/notes http/1.1
Content-Type: application/json


{
    "id": 4,
    "content": "big wow",
    "date": "2019-05-30T19:20:14.298Z",
    "important": true
}

###

DELETE http://localhost:3001/api/persons/1 http/1.1

###

POST http://localhost:3001/api/persons http/1.1
Content-Type: application/json


{
    "name":"jo",
    "number": "323"
}

###

GET http://localhost:3001/api/persons/5ffa2804d2f5a144e0f7fb7b http/1.1

###

PUT http://localhost:3001/api/persons/5ffa2804d2f5a144e0f7fb7b http/1.1
Content-Type: application/json

{
    "name":"vladimir",
    "number": "00000000000"
}

//{"_id":{"$oid":"5ffa2804d2f5a144e0f7fb7b"},"name":"vladimir","number":"213123232323","__v":{"$numberInt":"0"}}